version: '3.8'
services:
  frontend:
    build: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/voting
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
